### ISSUE TITLE
Many errors and warnings while compile source code with VS2013

### ISSUE THREAD

**Issue by tedaz** [fireice-uk/xmr-stak-cpu#157] opened 2017-06-15 02:47 UTC
> XMR-Stak should compile on any C++11 compliant compiler. Windows compiler is assumed to be MSVC 2015 CE. MSVC build environment is not vendored.
Does this means the W32 binary compiled with MSVC 2015CE? 
Currently the only available version on Microsoft website is Visual Studio Community 2017.

I've tried compile the source code with Visual Studio 2013, but there are many errors and warnings stopped the compile process. Could you please give more details on how to compile the source code?

**Comment by tedaz** [comment] 2017-06-15 05:21
I've already tried cmake and MinGW, there are also errors:
![xmr-cmake-mingw](https://user-images.githubusercontent.com/8318095/27166474-7906db74-51cd-11e7-96aa-3cf395be95b7.PNG)

**Comment by esfomeado** [comment] 2017-06-15 08:44
Just compile with Visual Studio Community 2017.

**Comment by psychocrypt** [comment] 2017-06-15 11:46
VS13 is not supporting C++11 tats the root of the issue. As @esfomeado wrote please switch ro VS17.
I will add fixes for VS17 and a documentation howto compile with all dependencies within the next two days.

**Comment by tedaz** [comment] 2017-06-16 02:37
@psychocrypt Looking forward to your documentation on how to compile the source code.
Currently, I'm tried below steps:

Install cmake-3.9.0-rc3-win64-x64
`cd xmr-stak-cpu-master
mkdir build
cd build
cmake .. -G "Visual Studio 15 Win64" -DMICROHTTPD_REQUIRED=OFF -DOpenSSL_REQUIRED=OFF`

Got some info and warnings:
`CMake Warning (dev) at CMakeLists.txt:25 (if):
  Policy CMP0054 is not set: Only interpret if() arguments as variables or
  keywords when unquoted.  Run "cmake --help-policy CMP0054" for policy
  details.  Use the cmake_policy command to set the policy and suppress this
  warning.

  Quoted variables like "MSVC" will no longer be dereferenced when the policy
  is set to NEW.  Since the policy is not set the OLD behavior will be used.
This warning is for project developers.  Use -Wno-dev to suppress it.

-- Looking for pthread.h
-- Looking for pthread.h - not found
-- Found Threads: TRUE
-- microhttpd NOT found: disable http server
-- Could NOT find OpenSSL, try to set the path to OpenSSL root folder in the system variable OPENSSL
_ROOT_DIR (missing: OPENSSL_CRYPTO_LIBRARY OPENSSL_INCLUDE_DIR)
-- Configuring done
-- Generating done`

Open "xmr-stak-cpu.sln" by Visual Studio 2017 Community Edition, press F7 (build solution), then got below fatal error:

`1>------ Build started: Project: xmr-stak-cpu, Configuration: Debug x64 ------
1>jpsock.obj : error LNK2019: unresolved external symbol __imp_WSAStartup referenced in function "void __cdecl sock_init(void)" (?sock_init@@YAXXZ)
1>jpsock.obj : error LNK2019: unresolved external symbol __imp_WSAGetLastError referenced in function "char const * __cdecl sock_strerror(char *,unsigned __int64)" (?sock_strerror@@YAPEBDPEAD_K@Z)
1>socket.obj : error LNK2019: unresolved external symbol __imp_closesocket referenced in function "void __cdecl sock_close(unsigned __int64)" (?sock_close@@YAX_K@Z)
1>socket.obj : error LNK2019: unresolved external symbol __imp_connect referenced in function "public: virtual bool __cdecl plain_socket::connect(void)" (?connect@plain_socket@@UEAA_NXZ)
1>socket.obj : error LNK2019: unresolved external symbol __imp_recv referenced in function "public: virtual int __cdecl plain_socket::recv(char *,unsigned int)" (?recv@plain_socket@@UEAAHPEADI@Z)
1>socket.obj : error LNK2019: unresolved external symbol __imp_send referenced in function "public: virtual bool __cdecl plain_socket::send(char const *)" (?send@plain_socket@@UEAA_NPEBD@Z)
1>socket.obj : error LNK2019: unresolved external symbol __imp_shutdown referenced in function "void __cdecl sock_close(unsigned __int64)" (?sock_close@@YAX_K@Z)
1>socket.obj : error LNK2019: unresolved external symbol __imp_socket referenced in function "public: virtual bool __cdecl plain_socket::set_hostname(char const *)" (?set_hostname@plain_socket@@UEAA_NPEBD@Z)
1>socket.obj : error LNK2019: unresolved external symbol __imp_getaddrinfo referenced in function "public: virtual bool __cdecl plain_socket::set_hostname(char const *)" (?set_hostname@plain_socket@@UEAA_NPEBD@Z)
1>socket.obj : error LNK2019: unresolved external symbol __imp_freeaddrinfo referenced in function "public: virtual bool __cdecl plain_socket::set_hostname(char const *)" (?set_hostname@plain_socket@@UEAA_NPEBD@Z)
1>D:\CPU\xmr-stak-cpu-master\build\bin\Debug\xmr-stak-cpu.exe : fatal error LNK1120: 10 unresolved externals
1>Done building project "xmr-stak-cpu.vcxproj" -- FAILED.
2>------ Skipped Build: Project: INSTALL, Configuration: Debug x64 ------
2>Project not selected to build for this solution configuration 
========== Build: 0 succeeded, 1 failed, 3 up-to-date, 1 skipped ==========`

**Comment by psychocrypt** [comment] 2017-06-16 05:35
the error should be fixed with #160 and a not final documentauon is in #161

**Comment by tedaz** [comment] 2017-06-16 06:53
@psychocrypt Thanks for your update. Why there are necessary pulls been required for compile on Windows, and what is the developers' native way to build the source code? Cross-compile on Linux or other methods? I assume the source code should be compiled without any error and without any modification, as there are exe binaries, how those binaries been built?

**Comment by psychocrypt** [comment] 2017-06-16 07:29
The reason that the windows build documentation and cmake fix is currently in separate pull requests is that both parts are in the state before the code is reviewed by a second developer. After @fireice-uk has reviewed my PR they get merged t the dev branch. The dev branch is something like a beta preview to the next release. Before we create a new release we create a release branch and test all changes again, if we think that all changes are stable we merge it the master and release it. After that there are no changes needed to compile on windows.

Currenlty the binaries are made with a handmade VS project. After both PR are marged the next binaries will compiled with cmake and everyone can do it easily.

**Comment by tedaz** [comment] 2017-06-16 07:48
@psychocrypt I finally tried below steps and only get on issue: missing openssl/ssl.
With Visual Studio 2017 CE (not using cmake), File->New->Project From Existing Code, select the source code folder. 
Then set the platform to x64.  
Build->Build Solution
The only error is "Cannot open include file: 'openssl/ssl.h': No such file or directory"

How to add the "-DOpenSSL_REQUIRED=OFF" option to VS during the import source code or build?

**Comment by psychocrypt** [comment] 2017-06-16 08:01
I don't know how it works in the GUI please use the command line and add `-DOpenSSL_REQUIRED=OFF`.
The reason why I am not investigate time how to use the gui is that it is hard for user to follow the instruction if the language of the gui is not english. The command line is more stable even if the gui layout is changed.

**Comment by tedaz** [comment] 2017-06-16 08:22
Is it possible to import existing code to Visual Studio by command line? I've googled but cannot find any info on this.

If I import the code by Visual Studio GUI, there will be missing openssl error, it seems the VS just ignored CMakeLists.txt and related switches/options.

If I use the cmake, there will be microhttpd NOT found error, but actually the microhttpd folder is there.

**Comment by psychocrypt** [comment] 2017-06-17 17:43
The way with cmake is the best way, we can automaticly search for dependencies and can explicit handle workarounds in cmake.

**Comment by psychocrypt** [comment] 2017-06-17 17:44
I close this issue because the issue is silved VS2013 is not supported (no C++11 is available)

**Closed by psychocrypt** 2017-06-17 17:44 UTC
