### ISSUE TITLE
If the pool rejects one result, xmr-stak never recovers

### ISSUE THREAD

**Issue by moobsen** [fireice-uk/xmr-stak-cpu#16] opened 2017-01-11 09:56 UTC
Hi,
I tried the miner and am very impressed with its performance. Unfortunately eventually the pool will start rejecting results and from this point on everything is rejected, until I manually restart the miner. 
Any idea, why that might be happening?
It would be nice if there'd exist an option, that the miner restarts once the pool starts rejecting results.

**Comment by fireice-uk** [comment] 2017-01-11 13:59
I will test that. Can you please post the log of the results report?

**Comment by fireice-uk** [comment] 2017-01-11 17:48
Sorry to say but the issue is with your, CPU (overclock), compiler, or pool. Please test more thoroughly before reporting a bug. Here are my test logs

Miner-side:
`[2017-01-11 17:37:17] : Starting single thread, affinity: 0.
[2017-01-11 17:37:17] : MEMORY ALLOC FAILED: mmap failed
[2017-01-11 17:37:17] : Starting single thread, affinity: 1.
[2017-01-11 17:37:17] : MEMORY ALLOC FAILED: mmap failed
[2017-01-11 17:37:17] : Connecting to pool 127.0.0.1:3333 ...
[2017-01-11 17:37:17] : Connected. Logging in...
[2017-01-11 17:37:21] : Difficulty changed. Now: 1024.
[2017-01-11 17:37:21] : New block detected.
[2017-01-11 17:38:10] : Result accepted by the pool.
[2017-01-11 17:39:11] : Result rejected by the pool.
[2017-01-11 17:39:56] : Result rejected by the pool.
[2017-01-11 17:40:54] : Result accepted by the pool.
[2017-01-11 17:41:25] : Result accepted by the pool.
[2017-01-11 17:41:32] : Result accepted by the pool.
[2017-01-11 17:42:08] : Result accepted by the pool.
[2017-01-11 17:43:27] : Result accepted by the pool.
[2017-01-11 17:43:31] : Result accepted by the pool.
[2017-01-11 17:43:35] : Result accepted by the pool.
RESULT REPORT
Difficulty       : 1024
Good results     : 8 / 10 (80.0 %)
Avg result time  : 38.2 sec
Pool-side hashes : 8192

Top 10 best results found:
|  0 |            45945 |  1 |            18188 |
|  2 |            12005 |  3 |             3800 |
|  4 |             3658 |  5 |             1919 |
|  6 |             1720 |  7 |             1111 |
|  8 |                0 |  9 |                0 |

Error details:
| Count |                       Error text |           Last seen |
|     1 | Test ERROR 1                     | 2017-01-11 17:39:11 |
|     1 | Test ERROR 2                     | 2017-01-11 17:39:56 |`

Pool side:
`{"method":"login","params":{"login":"","pass":"","agent":"xmr-stak-cpu/1.0"},"id":1}
{"id":0,"jsonrpc":"2.0","error":null,"result":{"id":"decafbad0","job":{"blob":"00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000","job_id":"00000000","target":"ffff3f00"},"status":"OK"}}
{"method":"submit","params":{"id":"decafbad0","job_id":"00000000","nonce":"58020000","result":"37b900f30bf1f1be17fe95f44d4cec7adfceb62764ae60907ec9b5e0276d0100"},"id":1}
{"id":1,"jsonrpc":"2.0","error":null,"result":{"status":"OK"}}
{"method":"submit","params":{"id":"decafbad0","job_id":"00000000","nonce":"18060000","result":"bab02186614ff9343681e77674077504e0d93fdcecd227facde46dae3e012300"},"id":1}
{"id":1,"jsonrpc":"2.0","error":{"code":-1,"message":"Test ERROR 1"}}
{"method":"submit","params":{"id":"decafbad0","job_id":"00000000","nonce":"d7080000","result":"1c72c96dae3e54e3883c4a44f010a70c23e98524d91f92fec1fc20b38f7c3b00"},"id":1}
{"id":1,"jsonrpc":"2.0","error":{"code":-1,"message":"Test ERROR 2"}}
{"method":"submit","params":{"id":"decafbad0","job_id":"00000000","nonce":"080c4000","result":"2dee3503f8c1366a76657d371be9894ac2b63cb7f6cbefc4b037b6d396172600"},"id":1}
{"id":1,"jsonrpc":"2.0","error":null,"result":{"status":"OK"}}
{"method":"submit","params":{"id":"decafbad0","job_id":"00000000","nonce":"310e0000","result":"7a9459af85dae3f2e456b6dae8d0ecaa80426e1ac8bffdc9fb2def688e232200"},"id":1}
{"id":1,"jsonrpc":"2.0","error":null,"result":{"status":"OK"}}
{"method":"submit","params":{"id":"decafbad0","job_id":"00000000","nonce":"430e0000","result":"b71c8a4c79560219f02e95506ad7f8abf9b44812f9adbe250a2f0b8a9cfa3a00"},"id":1}
{"id":1,"jsonrpc":"2.0","error":null,"result":{"status":"OK"}}
{"method":"submit","params":{"id":"decafbad0","job_id":"00000000","nonce":"65110000","result":"9aa0cbebd3b1b6b75973edd896a338169a8e066b06c522c9d00c5bda48e91100"},"id":1}
{"id":1,"jsonrpc":"2.0","error":null,"result":{"status":"OK"}}
{"method":"submit","params":{"id":"decafbad0","job_id":"00000000","nonce":"97130000","result":"dbf955746a48cc2ffcc02f17a7b68be869c0f439b4fc6e47f885d0ae78750500"},"id":1}
{"id":1,"jsonrpc":"2.0","error":null,"result":{"status":"OK"}}
{"method":"submit","params":{"id":"decafbad0","job_id":"00000000","nonce":"ae144000","result":"911808f84c69bf7c55c3c6330ecbc1dc85e20e86ee9cab8deabf49fc3d3e1100"},"id":1}
{"id":1,"jsonrpc":"2.0","error":null,"result":{"status":"OK"}}
{"method":"submit","params":{"id":"decafbad0","job_id":"00000000","nonce":"d0160000","result":"ecd11257120d90cff59be1b2b4449345a5c1c763c5919c776c32b72a659a0300"},"id":1}
{"id":1,"jsonrpc":"2.0","error":null,"result":{"status":"OK"}}` 

I will close the issue, but if you have any actual evidence of a problem, feel free to reopen.

**Comment by p4tr1kb** [comment] 2017-01-11 20:15
I'm seeing this also. 
    
    RESULT REPORT
    Difficulty : 19334
    Good results : 35 / 46 (76.1 %)
    Avg result time : 207.9 sec
    Pool-side hashes : 849830
    
    Top 10 best results found:
    | 0 | 3038288 | 1 | 1175436 |
    | 2 | 394762 | 3 | 334643 |
    | 4 | 291389 | 5 | 277151 |
    | 6 | 238773 | 7 | 158071 |
    | 8 | 120113 | 9 | 112295 |
    
    Error details:
    | Count | Error text | Last seen |
    | 11 | Unauthenticated | 2017-01-11 20:53:08 |

**Comment by fireice-uk** [comment] 2017-01-12 02:04
Ok. That was more helpful - thanks. For some reason the pool considers your user id is no longer valid.
Can you name the pool so that I can have a look at it myself?

**Comment by moobsen** [comment] 2017-01-12 09:54
```
Pool-side hashes : 756139

Top 10 best results found:
|  0 |           500718 |  1 |           468338 |
|  2 |           209996 |  3 |           133970 |
|  4 |            59820 |  5 |            55180 |
|  6 |            51866 |  7 |            47070 |
|  8 |            42924 |  9 |            41219 |

Error details:
| Count |                       Error text |           Last seen |
|   551 | Unauthenticated                  | 2017-01-12 04:39:05 |
```
```
[2017-01-11 15:30:34] : New block detected.
[2017-01-11 15:31:55] : Result accepted by the pool.
[2017-01-11 15:33:38] : Result accepted by the pool.
[2017-01-11 15:35:45] : New block detected.
[2017-01-11 15:36:27] : Result accepted by the pool.
[2017-01-11 15:37:11] : Result accepted by the pool.
[2017-01-11 15:43:39] : New block detected.
[2017-01-11 15:47:28] : New block detected.
[2017-01-11 15:48:37] : Difficulty changed. Now: 2247.
[2017-01-11 15:48:37] : New block detected.
[2017-01-11 15:50:45] : New block detected.
[2017-01-11 15:51:24] : New block detected.
[2017-01-11 15:52:08] : Difficulty changed. Now: 1597.
[2017-01-11 15:52:08] : New block detected.
[2017-01-11 15:53:14] : Result rejected by the pool.
[2017-01-11 15:59:36] : Result rejected by the pool.
[2017-01-11 16:02:14] : Result rejected by the pool.
[2017-01-11 16:03:22] : Result rejected by the pool.
[2017-01-11 16:03:31] : Result rejected by the pool.
[2017-01-11 16:04:18] : Result rejected by the pool.
[2017-01-11 16:04:21] : Result rejected by the pool.
[...]
```

```
CONNECTION REPORT
Connected since : 2017-01-11 04:35:21
Pool ping time  : 103 ms

Network error log:
Yay! No errors.
```

Same here. Pool is pool.minexmr.com. 
Something I also saw once in the logs, but don't find right now, was some switching between dev pool and user pool, not sure of the relevance of that.

**Comment by ku4eto** [comment] 2017-01-12 15:47
I get the same thing on my Windows VM with 2 assigned cores. Config uses LPM: True. I got around 400 counts of that error.

**Comment by fireice-uk** [comment] 2017-01-12 16:58
Basically the pool has configuration issues - you should ask your pool operator to either decrease the difficulty or increase the minerTimeout setting. You can clearly see that in moobsen log
```
[2017-01-11 15:37:11] : Result accepted by the pool.
[ .... ]
[2017-01-11 15:53:14] : Result rejected by the pool.
```
His miner didn't find a result for 16 minutes, whereas the default timeout is 10. Most likely the pool operator cranked up the difficulty while leaving the timeout value in place. 

Funny thing about cryptonote-universal-pool is that it is so crap that it won't drop a timeout miner - you will just sit on the connection forever.

I will add add a client-side connection drop on "Unauthenticated" error - buy you will still loose one result. Only proper pool configuration can prevent that one.

**Comment by PwnK** [comment] 2017-01-12 20:14
Which pool do you recommend? I'm using minexmr.com and having this same issue.

**Comment by fireice-uk** [comment] 2017-01-12 23:09
With cryptonote-universal-pool I would recommend any pool that let's you set your own difficulty. You can do that by putting your login as <wallet>.<diff>. Optimum difficulty is around 60x your hashrate.

One of the many crappy things about this pool software is that automatic difficulty will fluctuate instead of converging on a single value.

**Comment by ku4eto** [comment] 2017-01-13 06:29
The GPU difficulty using Wolfs miner on v.high end HW seems to be more or less static - either 50k, or 100k for me. Using the MultiCPUminer, the diff fluctuates a lot, and 1 share can take around 10-15 minutes. Getting one result rejected won't be fatal, its more important to have the miner re-initiate the connection.

**Comment by fireice-uk** [comment] 2017-01-13 14:34
Yes. It is just a "feature" of the pool's programming. Normally any competent server will detect a timeout, and then drop the connection. I'm not even sure what that timeout option is for, if it doesn't do that.

**Comment by fireice-uk** [comment] 2017-01-13 14:58
I pushed the fix for this issue.

**Comment by dimecoin** [comment] 2017-01-13 19:26
> If you want to know which pool I mine on, it is in the default config, not to pulg too much :P

Which pool?  Just curious.  

I use supportxmr.comand monerohash.com - both are well behaved.  No rejects in last 24 hours.

They have a starting diff (depending on port you connect to) and then try to do some type of dynamic difficulty, depending on how fast you are submitting shares.

**Comment by fireice-uk** [comment] 2017-01-14 03:00
supportxmr.com, since like everybody, I stare at the pool output, you can usually find me on the trollbox there :P 

supportxmr.com has 15 minute timeout and that seems to cover most cases.

**Comment by fireice-uk** [comment] 2017-01-14 17:37
I will close the issue as the fix is on the repo. Let me know if something continues to break.

**Closed** 2017-01-14 17:36 UTC

**Comment by sunk818** [comment] 2017-10-31 21:00
@fireice-uk 
> "Unauthenticated" error - but you will still loose one result. Only proper pool configuration can prevent that one.

Can you explain why you lose one result? Does reconnect to pool mean you get new session and jobid, so hash is not acceptable since jobid changed?
